### ISSUE TITLE
Combine `#birthdays` channel messages 🎂

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#416]
### Description

Every day, the StackBot sends a notification to the `#birthdays` channel wishing a happy birthday to each ColorStack member whose birthday it is. Currently, there is a separate message being sent for each member. There are some downsides to this:
- If members want to wish a happy birthday to everyone, they have to reply/react separately to each thread.
- Some members get more reactions/replies than others.

A small improvement we can make is combining all birthdays into 1 message.

### Acceptance Criteria

Here are examples of how the birthday message should look now:
- > We have `1` ColorStack birthday today -- everyone wish a happy birthday to `<@SLACK_USER_ID>`!
- > We have `2` ColorStack birthdays today -- everyone wish a happy birthday to `<@SLACK_USER_ID_1>` and `<@SLACK_USER_ID_2>`!
- > We have `3` ColorStack birthdays today -- everyone wish a happy birthday to `<@SLACK_USER_ID_1>`, `<@SLACK_USER_ID_2>` and `<@SLACK_USER_ID_3>`!

### Additional Context

The birthday notifications get sent in the [`sendBirthdayNotification`](https://github.com/colorstackorg/oyster/blob/main/packages/core/src/modules/member/use-cases/send-birthday-notification.ts#L8) function. We'll simply need to emit only 1 `notification.slack.send` job instead of multiple, and update the `message` field.

**Comment by JustinhSE** [comment]
I would say though, just because of the culture within ColorStack. Let’s say it was @ramiAbdou birthday but we also had 3 other birthdays the same day. We wouldn’t want 1 message combining all of them but the thread replies are like happy bday Rami mostly vs a member not many people know only getting one happy bday wish? Does that make sense?

**Comment by JustinhSE** [comment]
![IMG_6750](https://github.com/user-attachments/assets/b7bb0775-bbf1-40b1-9ac8-7ee8ecee1014)
![IMG_6751](https://github.com/user-attachments/assets/0a9e2669-55ca-4f96-8adb-6a2ceb581159)

**Comment by JustinhSE** [comment]
Like @ayoaru and @omar-elbaz are valued and active members….. does this make sense? I feel a generic happy bday would lose that sense of intimacy we share within the community channel.

**Comment by tomas-salgado** [comment]
@JustinhSE Hmm I see what you're saying but wouldn't it already be the case that some users are getting more replies than others? The intent isn't necessarily to reduce the sense of community but rather engage more with everyone even if it's not a very active member

**Comment by ayoaru** [comment]
I have noticed that people don't engage as much with the other birthdays if they fall on the same day as a more active member... Disparity in comments makes a bit more sense, but the disparity in reactions is off putting imo since reactions are an easy thing to do. That part feels like the other person gets overshadowed when it's their birthday too.

This is tricky though. Maybe have the community vote on the issue?

**Comment by JustinhSE** [comment]
@tomas-salgado i get what you are saying. I am just saying if we condensed it into 1 msg it would look kinda odd if members wished let’s say 1 person by @ mentioning them if they were a pretty active member. The issue is overshadowing as @ayoaru is saying. I am glad to work on this but it is a tricky issue that I do think the community should vote on as well

**Comment by iperalta7** [comment]
Just putting my thoughts out there, I also believe a community vote would be fine. Looking at it from another perspective, typically companies/groups send out a single email listing everyone who has opted in, especially when many people share the same birthday. Those who wish to personally mention the birthday individual can do so separately, which can detract from the community feeling a bit. As the community continues to grow, there is a chance that individuals posted first may be overshadowed.

If this was the ages of email still, you wouldn't want to clutter it up. 😂
