### ISSUE TITLE
Share member contact info with Chapter Leaders 📬

### ISSUE THREAD

**Issue by omar-elbaz** [colorstackorg/oyster#51]
### Description

✅ It would be great to implement something that gives permission for ColorStack to share a Member's Email with local ColorStack Chapter leaders.

### Problem / Value Proposition

📩 Chapter Leaders (like myself) are always looking for ways to engage with the community and to reach as many people as possible. In my case there are hundreds if not upwards of a thousand ColorStack members across the NYC metro area. But Johana can't just give me their contact info for legal reasons. Implementing this will help bridge the gap between chapter leaders, and the community. 

### Additional Context

💻 This will likely be implemented as a checkbox somewhere in this folder [here](apps/member-profile/app/routes) my guess is either the [emails](apps/member-profile/app/routes/_profile.profile.emails.tsx) page or the [general](apps/member-profile/app/routes/_profile.profile.general.tsx) page

- You can reference how we built the component for the [BirthdateNotification](https://github.com/colorstackorg/oyster/blob/e3ca5dd64ffb53cb75e139c374a3c146d78a2d3c/apps/member-profile/app/shared/components/profile.personal.tsx#L8)
- The checkbox will store a boolean value in the database, and it's default should be True.
- This will require a Database migration similar to [this](packages/core/src/infrastructure/database/migrations/2024-03-18T19:45:26Z-birthday-default.ts) one. 

Good and luck and be sure to see our [contributing](https://github.com/colorstackorg/oyster/blob/main/CONTRIBUTING.md) guide!👋

**Comment by tomas-salgado** [comment]
Cool idea! Would the scope of this work be solely implementing the ColorStack member side of it, where members can opt into having their email shared? Or do we also want to think about some kind of interface for chapter leaders to access or contact these shared emails?

**Comment by omar-elbaz** [comment]
Great question, I think a reasonable mvp would be just the member side of things. We can work with Johana and @ramiAbdou in the future to see the best way for the chapter leaders to get access to the info.

**Comment by tomas-salgado** [comment]
That sounds good, I can take on this issue and implement the member side

**Comment by omar-elbaz** [comment]
Awesome bro, give me a shout whenever! Can't wait for this :)

**Comment by ramiAbdou** [comment]
This is something Johana has requested a few times, so definitely think it makes sense to work on! and I agree that the scope should only be allowing members to opt into having their emails shared for now. 👍

I only have one question with this one: do you guys think it makes sense for this to be default opted-in? I feel like that's the equivalent of just sharing emails without their consent, but I don't know. At the very least, feel like we should have an email notification that goes out them being opted in.

**Comment by omar-elbaz** [comment]
I think a default opt in would be ideal but I also agree with you, an email notification might be the perfect medium.

**Comment by tomas-salgado** [comment]
I actually think it might be better to have the default be opt out. From a user perspective I know it's definitely irritating to be unexpectedly added to random email lists. Also, it might make it less clear for new members to distinguish between main ColorStack emails versus emails from local chapters. 

My thoughts would be to have this default opt-out, but perhaps next to the checkbox (and/or during registration) we can write something like 
`Share my email with Chapter Leaders to connect with ColorStack communities at local universities! (Recommended)`
That way we encourage the feature, without it seeming defaulted/required.

Any thoughts on this? (Also, any feedback on what the checkbox message should be? This is what I have so far)

**Comment by ramiAbdou** [comment]
Yeah I definitely get what you're saying @tomas-salgado!

There's definitely 2 groups we have to solve for in this: new members and existing members.

For new members, I definitely agree that we should update the application to add a checkbox which asks that permission up front!

For existing members, I'm a little torn. Because the reality is that if it's default opt-out, then there likely won't be many people that opt-in because it's generally hard to get people to act based on emails. I feel like this would be different than getting randomly added to lists (I know the feeling) just because we would be clear in our email communication that goes out that lets them know that they can opt out (and we would send them a link to do so). Another thing to consider is that this pool of "existing members" is in reality reduced to graduation year of >= 2024. Additionally, if we assume that a decent amount of ColorStack are already connected to their chapters, then this pool is then even smaller.

That last point could also be an argument for making it default `false`, because if the pool is that small then how beneficial would it be to automatically opt them in. 😅

Let me know how you feel about the above  - I can definitely see both sides being valid and am okay proceeding either way!

**Comment by tomas-salgado** [comment]
Ah, I see your point here. I'm now convinced that for existing members we should have the default `true`. I think my argument before was more relevant to new members, but adding this as part of the application resolves this. But in the case of existing members, I think as long as there is an email notification, there wouldn't be any complaints with learning about in-person community events!
