### ISSUE TITLE
Connect GitHub account to the Member Profile 🔀

### ISSUE THREAD

**Issue by ramiAbdou** [colorstackorg/oyster#64]
### Description

We need to support connecting a GitHub account to a member's ColorStack account. This will be the beginning of many such integrations in the future!

### Acceptance Criteria

This issue should:
- Add an `Integrations` page to the "profile" section of the Member Profile.
- Implement the ability to connect a GitHub account using OAuth.
- Store some reference to that GitHub account (ie: `github_id`) on the member record.
- Overwrite the existing `github_url` on the member record when the account is connected.
- Disable the GitHub URL field from the "socials" page, and add a description that includes the ability to connect in the integrations page. 
![GitHub URL Field](https://github.com/colorstackorg/oyster/assets/38056800/16db6f67-544d-4277-9623-06fbaf6d103f)

**Comment by M00ny0z** [comment]
I would love to work on this

**Comment by ramiAbdou** [comment]
That sounds great - thank you! Before I assign it to you, can you confirm that you're a ColorStack member? I couldn't deduce who you were from your GitHub username. 😭

**Comment by M00ny0z** [comment]
https://app.colorstack.io/directory/WOsiK4TpTLYaXLsz5ZLT1

**Comment by ramiAbdou** [comment]
Awesome, appreciate it - just assigned to you! Connecting your GitHub account would actually solve this 😜

**Comment by M00ny0z** [comment]
Have you already registered an OAuth App under the colorstack org?

**Comment by ramiAbdou** [comment]
Not yet, but for development please generate a GitHub app on your account so that you have your own set of credentials!

**Comment by M00ny0z** [comment]
Got it. Regarding
`Disable the GitHub URL field from the "socials" page, and add a description that includes the ability to connect in the integrations page.`
Should I disable it completely and add said description or should I only disable it once the user has connected their Github account?

**Comment by M00ny0z** [comment]
Exactly what I had in mind. I apologize for the delay in my PR, I haven't worked with OAuth or Remix, I've been reading online about them and following tutorials. Do you prefer questions here or on slack?

Here's my plan for the implementation:
- I create an integrations page with a button link to the Github OAuth page, the Github OAuth is setup to redirect to the below route when the user successfully logins into Github
- I create a route called `/Integrations/Github/` with a loader function
- 1. Said route checks if the URL has an access code piece and proceeds, redirects to the integration page otherwise
- 2. Then it makes a request to the Github API to trade the access code for an access token
- 3. Uses the access token to make a request to the Github API for the users Github info
- 4. Assuming the requests have been successful, it updates the member record accordingly
- Redirects to the integration page when done
Am I going in the right direction for how things should be done in Remix? The way I've set things up, its only for adding the users Github as part of their account, not for using OAuth for logging in (I do realize that can be done in the future but I was thinking it would make sense to use `remix-auth-oauth2` for that instead)

**Comment by ramiAbdou** [comment]
I know I already responded to you via DM, but just wanted to say don't worry too much about how the UI looks. Obviously we'd love to have some Figma designs to share, but feel free to just get some initial UI started and I'll refine it!
